// <auto-generated />
using System;
using BinasJc.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinasJc.DAL.Migrations
{
    [DbContext(typeof(BinasJcContext))]
    [Migration("20241107184442_UpdateDecimalPrecision")]
    partial class UpdateDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BinasJc.Model.Bicicleta", b =>
                {
                    b.Property<int>("BicicletaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BicicletaID"));

                    b.Property<string>("BeaconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstacaoID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BicicletaID");

                    b.HasIndex("EstacaoID");

                    b.ToTable("Bicicletas");
                });

            modelBuilder.Entity("BinasJc.Model.Estacao", b =>
                {
                    b.Property<int>("EstacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstacaoID"));

                    b.Property<int>("BicicletasDisponiveis")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NomeEstacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstacaoID");

                    b.ToTable("Estacoes");
                });

            modelBuilder.Entity("BinasJc.Model.Ponto", b =>
                {
                    b.Property<int>("PontoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PontoID"));

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioDestinoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioOrigemID")
                        .HasColumnType("int");

                    b.HasKey("PontoID");

                    b.HasIndex("UsuarioDestinoID");

                    b.HasIndex("UsuarioOrigemID");

                    b.ToTable("Pontos");
                });

            modelBuilder.Entity("BinasJc.Model.Reserva", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaID"));

                    b.Property<int>("BicicletaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraRetirada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DistanciaPercorrida")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("EstacaoDevolucaoID")
                        .HasColumnType("int");

                    b.Property<int>("EstacaoRetiradaID")
                        .HasColumnType("int");

                    b.Property<int>("PontosGanhos")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID");

                    b.HasIndex("BicicletaID");

                    b.HasIndex("EstacaoDevolucaoID");

                    b.HasIndex("EstacaoRetiradaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BinasJc.Model.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BinasJc.Model.Bicicleta", b =>
                {
                    b.HasOne("BinasJc.Model.Estacao", "Estacao")
                        .WithMany()
                        .HasForeignKey("EstacaoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacao");
                });

            modelBuilder.Entity("BinasJc.Model.Ponto", b =>
                {
                    b.HasOne("BinasJc.Model.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinasJc.Model.Usuario", "UsuarioOrigem")
                        .WithMany()
                        .HasForeignKey("UsuarioOrigemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigem");
                });

            modelBuilder.Entity("BinasJc.Model.Reserva", b =>
                {
                    b.HasOne("BinasJc.Model.Bicicleta", "Bicicleta")
                        .WithMany()
                        .HasForeignKey("BicicletaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinasJc.Model.Estacao", "EstacaoDevolucao")
                        .WithMany()
                        .HasForeignKey("EstacaoDevolucaoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinasJc.Model.Estacao", "EstacaoRetirada")
                        .WithMany()
                        .HasForeignKey("EstacaoRetiradaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinasJc.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bicicleta");

                    b.Navigation("EstacaoDevolucao");

                    b.Navigation("EstacaoRetirada");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
